<?php
require 'config.php';

$data = json_decode(file_get_contents("php://input"), true);

if (!isset($data['name']) || !isset($data['email']) || !isset($data['password']) || !isset($data['age'])) {
    echo json_encode(["error" => "Missing fields"]);
    exit();
}

$name = $data['name'];
$email = $data['email'];
$password = password_hash($data['password'], PASSWORD_DEFAULT);
$age = intval($data['age']);

// Check if user exists
$check = $conn->prepare("SELECT id FROM users WHERE email = ?");
$check->bind_param("s", $email);
$check->execute();
$check->store_result();

if ($check->num_rows > 0) {
    echo json_encode(["error" => "Email already exists"]);
    exit();
}
$check->close();

// Insert User
$stmt = $conn->prepare("INSERT INTO users (name, email, password_hash, age) VALUES (?, ?, ?, ?)");
$stmt->bind_param("sssi", $name, $email, $password, $age);

if ($stmt->execute()) {
    $user_id = $stmt->insert_id;
    
    // Initialize Progress
    $init_json = json_encode([
        'inventory' => [],
        'dailyChallenges' => [], // Will be generated by frontend and synced later
        'completedTopics' => [],
        'vocabularyBank' => [],
        'stats' => [
            'savedLessons' => 0, 'lessonsCompleted' => 0, 
            'currentLevelProgress' => 0, 'phase1Progress' => 0, 
            'phase2Progress' => 0, 'phase3Progress' => 0
        ],
        'achievements' => ['lessonsCompleted' => 0, 'wordsLearned' => 0, 'quizPerfect' => 0],
        'placementTestCompleted' => false
    ]);
    
    $prog = $conn->prepare("INSERT INTO user_progress (user_id, json_data) VALUES (?, ?)");
    $prog->bind_param("is", $user_id, $init_json);
    $prog->execute();

    echo json_encode(["success" => true, "user_id" => $user_id]);
} else {
    echo json_encode(["error" => "Error registering user"]);
}

$stmt->close();
$conn->close();
?>
